### ISSUE TITLE
Support SinkRecord field references from PK 

### ISSUE THREAD

**Issue by stampy88** [datamountaineer/kafka-connect-query-language#18]
When writing a KCQL statement it would be very handy to be able to reference field off of the SinkRecord. For example:

`INSERT INTO test-map SELECT * FROM test-topic PK record.key WITHFORMAT AVRO STOREAS IMAP`
 would use the key from the record as the primary key.

**Comment by andrewstevenson** [comment]
@stampy88 Kcql supports this we'd actually just need to enable it in the sink (hazelcast i assume)

**Comment by stampy88** [comment]
Ah, OK. I didn't realize that. I'll look through the Hazelcast sink and try and get a PR together. @andrewstevenson is there a doc that has which fields are available from the record and how to reference it?

**Comment by andrewstevenson** [comment]
We already support it https://github.com/datamountaineer/stream-reactor/blob/master/kafka-connect-hazelcast/src/main/scala/com/datamountaineer/streamreactor/connect/hazelcast/writers/Writer.scala

But its missing from the docs http://docs.datamountaineer.com/en/latest/hazelcast.html

**Comment by stampy88** [comment]
Cool, thanks
