### ISSUE TITLE
Table names using : are not allowed.

### ISSUE THREAD

**Issue by eKIK** [datamountaineer/kafka-connect-query-language#19]
In HBase the : is used as a namespace delimiter, so it's very important to be able to have it as part of the table name.

Judging from ConnectorParser.g4, table_name is defined as:
`table_name
   : ID | TOPICNAME
   ;
`

...where ID and TOPICNAME are defined in ConnectorLexer.g4 as:
`ID
   : ( 'a' .. 'z' | 'A' .. 'Z' | '_' | '0' .. '9' )+
   ;

TOPICNAME
   : ( 'a' .. 'z' | 'A' .. 'Z' | '_' | '0' .. '9'| '.' | '-' | '+' | '/' |'{'|'}' )+
   ;
`

Based on
https://github.com/apache/kafka/blob/41e676d29587042994a72baa5000a8861a075c8c/core/src/main/scala/kafka/common/Config.scala it seems like the only valid characters for a Kafka topic name are alphanumerics and . _ -

This means the current implementation are accepting a bit too many symbols for a topic name.
At the same time it doesn't accept : as part of table names.

Would it perhaps make sense to define TABLENAME and include : there as well, and at the same time correct TOPICNAME? I've seen it used in a couple of other places, so perhaps it's not a great idea removing the symbols not allowed by a topic.

My main issue here is not allowing : in table names...so simply adding that symbol to TOPICNAME would be a great first step. It's not a valid symbol to have in a topic, but neither are a lot of the others that are already allowed.

**Comment by stheppi** [comment]
@eKIK 
The fix has been applied.
We are aware of the topic naming restriction however KCQL covers sinks and sources. Sources like JMS would allow a few  extra characters - hence TOPICNAME token accepts them

**Comment by eKIK** [comment]
@stheppi Ah yeah, I didn't think about using KCQL for sources like JMS - what you're saying makes sense.
